# Generated by Django 5.1.7 on 2025-04-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlist',
            name='server_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serverlist',
            name='server_invite_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
