# Generated by Django 5.1.7 on 2025-04-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_playerlist_created_by_playerlist_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverlist',
            name='server_is_vanilla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverlist',
            name='server_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
