# Generated by Django 5.1.7 on 2025-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_serverlist_server_is_vanilla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerservermap',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerservermap',
            name='banned_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerservermap',
            name='banned_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerservermap',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playerlist',
            name='player_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
