# Generated by Django 5.1.7 on 2025-04-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_playerservermap_banned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerservermap',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
