# Generated by Django 5.1.7 on 2026-08-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_playerservermap_is_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerservermap',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
